project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /langs/en-US.yaml
    translation: /langs/%locale%.yaml

  - source: /website-langs/en-US.yaml
    translation: /website-langs/%locale%.yaml